// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/torrent-store.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The push response message containing info hash of the pushed torrent file
type PushReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      string                 `protobuf:"bytes,1,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushReply) Reset() {
	*x = PushReply{}
	mi := &file_proto_torrent_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReply) ProtoMessage() {}

func (x *PushReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReply.ProtoReflect.Descriptor instead.
func (*PushReply) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{0}
}

func (x *PushReply) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

// The push request message containing the torrent and expire duration is seconds
type PushRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Torrent []byte                 `protobuf:"bytes,1,opt,name=torrent,proto3" json:"torrent,omitempty"`
	// Deprecated: Marked as deprecated in proto/torrent-store.proto.
	Expire        int32 `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_proto_torrent_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{1}
}

func (x *PushRequest) GetTorrent() []byte {
	if x != nil {
		return x.Torrent
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/torrent-store.proto.
func (x *PushRequest) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

// The pull request message containing the infoHash
type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      string                 `protobuf:"bytes,1,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_proto_torrent_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{2}
}

func (x *PullRequest) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

// The pull response message containing the torrent
type PullReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrent       []byte                 `protobuf:"bytes,1,opt,name=torrent,proto3" json:"torrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullReply) Reset() {
	*x = PullReply{}
	mi := &file_proto_torrent_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullReply) ProtoMessage() {}

func (x *PullReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullReply.ProtoReflect.Descriptor instead.
func (*PullReply) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{3}
}

func (x *PullReply) GetTorrent() []byte {
	if x != nil {
		return x.Torrent
	}
	return nil
}

// The check request message containing the infoHash
type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      string                 `protobuf:"bytes,1,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_torrent_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{4}
}

func (x *CheckRequest) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

// The check response message containing existance flag
type CheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReply) Reset() {
	*x = CheckReply{}
	mi := &file_proto_torrent_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReply) ProtoMessage() {}

func (x *CheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReply.ProtoReflect.Descriptor instead.
func (*CheckReply) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{5}
}

func (x *CheckReply) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// The touch response message
type TouchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchReply) Reset() {
	*x = TouchReply{}
	mi := &file_proto_torrent_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchReply) ProtoMessage() {}

func (x *TouchReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchReply.ProtoReflect.Descriptor instead.
func (*TouchReply) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{6}
}

// The touch request message containing the torrent and expire duration is seconds
type TouchRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	InfoHash string                 `protobuf:"bytes,1,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	// Deprecated: Marked as deprecated in proto/torrent-store.proto.
	Expire        int32 `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchRequest) Reset() {
	*x = TouchRequest{}
	mi := &file_proto_torrent_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchRequest) ProtoMessage() {}

func (x *TouchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchRequest.ProtoReflect.Descriptor instead.
func (*TouchRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{7}
}

func (x *TouchRequest) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/torrent-store.proto.
func (x *TouchRequest) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

// The files request message containing the infoHash
type FilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      string                 `protobuf:"bytes,1,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesRequest) Reset() {
	*x = FilesRequest{}
	mi := &file_proto_torrent_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesRequest) ProtoMessage() {}

func (x *FilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesRequest.ProtoReflect.Descriptor instead.
func (*FilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{8}
}

func (x *FilesRequest) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

// A single file entry in a torrent manifest. path is the full path
// components including the torrent name as the first element (matching
// the rest-api file path convention). length is the file size in bytes.
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Length        int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_torrent_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{9}
}

func (x *FileInfo) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *FileInfo) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// The files response message containing the torrent name and its file
// manifest. Piece hashes are intentionally omitted — they are not needed
// for listing and dominate the .torrent size.
type FilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesReply) Reset() {
	*x = FilesReply{}
	mi := &file_proto_torrent_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesReply) ProtoMessage() {}

func (x *FilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesReply.ProtoReflect.Descriptor instead.
func (*FilesReply) Descriptor() ([]byte, []int) {
	return file_proto_torrent_store_proto_rawDescGZIP(), []int{10}
}

func (x *FilesReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilesReply) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_proto_torrent_store_proto protoreflect.FileDescriptor

const file_proto_torrent_store_proto_rawDesc = "" +
	"\n" +
	"\x19proto/torrent-store.proto\"'\n" +
	"\tPushReply\x12\x1a\n" +
	"\binfoHash\x18\x01 \x01(\tR\binfoHash\"C\n" +
	"\vPushRequest\x12\x18\n" +
	"\atorrent\x18\x01 \x01(\fR\atorrent\x12\x1a\n" +
	"\x06expire\x18\x02 \x01(\x05B\x02\x18\x01R\x06expire\")\n" +
	"\vPullRequest\x12\x1a\n" +
	"\binfoHash\x18\x01 \x01(\tR\binfoHash\"%\n" +
	"\tPullReply\x12\x18\n" +
	"\atorrent\x18\x01 \x01(\fR\atorrent\"*\n" +
	"\fCheckRequest\x12\x1a\n" +
	"\binfoHash\x18\x01 \x01(\tR\binfoHash\"$\n" +
	"\n" +
	"CheckReply\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\f\n" +
	"\n" +
	"TouchReply\"F\n" +
	"\fTouchRequest\x12\x1a\n" +
	"\binfoHash\x18\x01 \x01(\tR\binfoHash\x12\x1a\n" +
	"\x06expire\x18\x02 \x01(\x05B\x02\x18\x01R\x06expire\"*\n" +
	"\fFilesRequest\x12\x1a\n" +
	"\binfoHash\x18\x01 \x01(\tR\binfoHash\"6\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\"A\n" +
	"\n" +
	"FilesReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\x05files\x18\x02 \x03(\v2\t.FileInfoR\x05files2\xa4\x01\n" +
	"\fTorrentStore\x12\"\n" +
	"\x04Push\x12\f.PushRequest\x1a\n" +
	".PushReply\"\x00\x12\"\n" +
	"\x04Pull\x12\f.PullRequest\x1a\n" +
	".PullReply\"\x00\x12%\n" +
	"\x05Touch\x12\r.TouchRequest\x1a\v.TouchReply\"\x00\x12%\n" +
	"\x05Files\x12\r.FilesRequest\x1a\v.FilesReply\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_proto_torrent_store_proto_rawDescOnce sync.Once
	file_proto_torrent_store_proto_rawDescData []byte
)

func file_proto_torrent_store_proto_rawDescGZIP() []byte {
	file_proto_torrent_store_proto_rawDescOnce.Do(func() {
		file_proto_torrent_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_torrent_store_proto_rawDesc), len(file_proto_torrent_store_proto_rawDesc)))
	})
	return file_proto_torrent_store_proto_rawDescData
}

var file_proto_torrent_store_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_torrent_store_proto_goTypes = []any{
	(*PushReply)(nil),    // 0: PushReply
	(*PushRequest)(nil),  // 1: PushRequest
	(*PullRequest)(nil),  // 2: PullRequest
	(*PullReply)(nil),    // 3: PullReply
	(*CheckRequest)(nil), // 4: CheckRequest
	(*CheckReply)(nil),   // 5: CheckReply
	(*TouchReply)(nil),   // 6: TouchReply
	(*TouchRequest)(nil), // 7: TouchRequest
	(*FilesRequest)(nil), // 8: FilesRequest
	(*FileInfo)(nil),     // 9: FileInfo
	(*FilesReply)(nil),   // 10: FilesReply
}
var file_proto_torrent_store_proto_depIdxs = []int32{
	9,  // 0: FilesReply.files:type_name -> FileInfo
	1,  // 1: TorrentStore.Push:input_type -> PushRequest
	2,  // 2: TorrentStore.Pull:input_type -> PullRequest
	7,  // 3: TorrentStore.Touch:input_type -> TouchRequest
	8,  // 4: TorrentStore.Files:input_type -> FilesRequest
	0,  // 5: TorrentStore.Push:output_type -> PushReply
	3,  // 6: TorrentStore.Pull:output_type -> PullReply
	6,  // 7: TorrentStore.Touch:output_type -> TouchReply
	10, // 8: TorrentStore.Files:output_type -> FilesReply
	5,  // [5:9] is the sub-list for method output_type
	1,  // [1:5] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_torrent_store_proto_init() }
func file_proto_torrent_store_proto_init() {
	if File_proto_torrent_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_torrent_store_proto_rawDesc), len(file_proto_torrent_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_torrent_store_proto_goTypes,
		DependencyIndexes: file_proto_torrent_store_proto_depIdxs,
		MessageInfos:      file_proto_torrent_store_proto_msgTypes,
	}.Build()
	File_proto_torrent_store_proto = out.File
	file_proto_torrent_store_proto_goTypes = nil
	file_proto_torrent_store_proto_depIdxs = nil
}
